global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: "linguicards-api"
    metrics_path: "/metrics"
    static_configs:
      - targets:
          - "host.docker.internal:8080"
    relabel_configs:
      - target_label: instance
        replacement: linguicards-api

